# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: RunsInContainer
  container:
    image: "linuxbrew/brew"
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      architecture: x64
  - script: |
      sudo HOMEBREW_NO_AUTO_UPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew install python@3.8
      sudo /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/pip3 install --upgrade setuptools \
      -U pip --no-cache-dir \
      pylint .
    displayName: Install Python packages
    env:
      HOMEBREW_NO_AUTOUPDATE: 1
  - script: |
      cd bin
      pylint long-to-linked tigmint-cut tigmint_molecule.py tigmint_molecule_paf.py
      echo $?
      cd ../
    displayName: Run pylint
  - script: |
      sudo /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/pip3 install pytest
      sudo HOMEBREW_NO_AUTOUPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew tap brewsci/bio 
      sudo HOMEBREW_NO_AUTOUPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew install bedtools bwa samtools gnu-time minimap2
      export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
      export PATH=/home/linuxbrew/.linuxbrew/opt/python@3.8/bin:$PATH
      echo $PATH
      cd tests
      pytest -vs tigmint_test.py
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    displayName: Run pytests
  - script: |
      curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-11 main"
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends clang-format-11 clang-tidy-11
      sudo ln -s clang-format-11 /usr/bin/clang-format
      sudo ln -s clang-tidy-11 /usr/bin/clang-tidy
    displayName: Install clang-format and clang-tidy
  - script: make -C src all
    displayName: Compile C++ executables
  - script: make -C src lint
    displayName: Run clang-format and clang-tidy

