# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job:
  displayName: ubuntu-16.04
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name tigmint_CI
    displayName: Create Anaconda environment

  - script: |
      source activate tigmint_CI
      conda install --yes --quiet --name tigmint_CI python=3.8 pylint
      conda install --yes --quiet --name tigmint_CI -c bioconda --file requirements.txt
    displayName: Install Anaconda packages
  - script: |
      source activate tigmint_CI
      cd bin
      pylint long-to-linked tigmint-cut tigmint_molecule.py tigmint_molecule_paf.py
      echo $?
      cd ../
    displayName: Run pylint
  - script: |
      source activate tigmint_CI
      conda install --yes --quiet --name tigmint_CI-c bioconda pytest bedtools bwa samtools minimap2
      echo $PATH
      cd tests
      pytest -vs tigmint_test.py
    displayName: Run pytests
  - script: |
      curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-11 main"
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends clang-format-11 clang-tidy-11
      sudo ln -s clang-format-11 /usr/bin/clang-format
      sudo ln -s clang-tidy-11 /usr/bin/clang-tidy
    displayName: Install clang-format and clang-tidy
  - script: make -C src all
    displayName: Compile C++ executables
  - script: make -C src lint
    displayName: Run clang-format and clang-tidy

