# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: RunsInContainer
  container:
    image: "linuxbrew/brew"
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
      architecture: x64
  - script: |
      sudo HOMEBREW_NO_AUTO_UPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew install python
      sudo /home/linuxbrew/.linuxbrew/bin/pip3  install --upgrade setuptools \
      - U pip --no-cache-dir \
      pylint .
    displayName: Install Python Packages
    env:
      HOMEBREW_NO_AUTOUPDATE: 1
  - script: |
      cd bin
      pylint long-to-linked read_fasta.py tigmint-molecule \
      tigmint-cut tigmint-arcs-tsv
    displayName: Run pylint

# Scripts for tests -- pytest


    

    
  