# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name tigmint_CI
    displayName: Create Anaconda environment
  - script: |
      curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-11 main"
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends clang-format-13 clang-tidy-13
      sudo ln -sf clang-format-13 /usr/bin/clang-format
      sudo ln -sf clang-tidy-13 /usr/bin/clang-tidy
    displayName: Install clang-format and clang-tidy
  - script: make -C src all
    displayName: Compile C++ executables
  - script: make -C src lint
    displayName: Run clang-format and clang-tidy
  - script: |
      source activate tigmint_CI
      conda install --yes --quiet --name tigmint_CI python=3.7 pylint
      conda install --yes --quiet --name tigmint_CI -c conda-forge -c bioconda --file requirements.txt
    displayName: Install Anaconda packages
  - script: |
      source activate tigmint_CI
      cd bin
      pylint tigmint-cut tigmint_molecule.py tigmint_molecule_paf.py tigmint_estimate_dist.py
      echo $?
      cd ../
    displayName: Run pylint
  - script: |
      source activate tigmint_CI
      conda install --yes --quiet --name tigmint_CI -c conda-forge -c bioconda pytest bedtools bwa samtools=1.9 minimap2
      echo $PATH
      cd tests
      pytest -vs tigmint_test.py
    displayName: Run pytests
