# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: RunsInContainer
  container:
    image: "linuxbrew/brew"
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      architecture: x64
  - script: |
      sudo HOMEBREW_NO_AUTO_UPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew install python
      sudo /home/linuxbrew/.linuxbrew/bin/pip3 install --upgrade setuptools \
      -U pip --no-cache-dir \
      pylint .
    displayName: Install Python packages
    env:
      HOMEBREW_NO_AUTOUPDATE: 1
  - script: |
      export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
      echo path:
      echo $PATH
      sudo /home/linuxbrew/.linuxbrew/bin/pip3 install pytest
      sudo HOMEBREW_NO_AUTOUPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew install bedtools bwa samtools gnu-time
      cd tests/tigmint/pytest
      pytest -vs tigmint_test.py
      cd ../../../
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    displayName: Testing tigmint
  - script: |
      export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
      echo path:
      echo $PATH
      sudo /home/linuxbrew/.linuxbrew/bin/pip3 install pytest
      sudo HOMEBREW_NO_AUTOUPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew install bedtools samtools gnu-time
      sudo HOMEBREW_NO_AUTOUPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew tap brewsci/bio
      sudo HOMEBREW_NO_AUTOUPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew install minimap2
      cd tests/tigmint-long/pytest
      pytest -vs tigmint-long_test.py
      cd ../../../
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    displayName: Testing tigmint-long