# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: RunsInContainer
  container:
    image: "linuxbrew/brew"
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      architecture: x64
  - script: |
      sudo HOMEBREW_NO_AUTO_UPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew install python@3.8
      sudo /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/pip3 install --upgrade setuptools \
      -U pip --no-cache-dir \
      pylint .
    displayName: Install Python packages
    env:
      HOMEBREW_NO_AUTOUPDATE: 1
  - script: |
      cd bin
      pylint tigmint_molecule.py long-to-linked tigmint-cut tigmint-molecule tigmint-molecule-paf
      cd ../
    displayName: Run pylint
  - script: |
      sudo /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/pip3 install pytest
      sudo HOMEBREW_NO_AUTOUPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew tap brewsci/bio 
      sudo HOMEBREW_NO_AUTOUPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew install bedtools bwa samtools gnu-time minimap2
      export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
      export PATH=/home/linuxbrew/.linuxbrew/opt/python@3.8/bin:$PATH
      echo $PATH
      cd tests
      pytest -vs tigmint_test.py
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    displayName: Run pytests
