---
title: Break scaffolds at loci not supported by molecules
author: Shaun Jackman
output:
  html_document:
    keep_md: true
params:
  input_tsv:
    label: "Input TSV file of breakpoints"
    value: "breakpoints.tsv"
    input: text
  input_fai:
    label: "Input FAI file of scaffold sizes"
    value: "draft.fa.fai"
    input: text
  output_bed:
    label: "Output BED file of breaktig coordinates"
    value: "breakpoints.tigs.bed"
    input: text
---

```{r setup, message=FALSE}
library(dplyr)
library(knitr)
library(readr)
library(tidyr)
library(uniqtag)

knit_print.data.frame <- function(x, ...) kable(x) %>% paste(collapse = "\n") %>% asis_output
input_tsv <- params$input_tsv
input_fai <- params$input_fai
output_bed <- params$output_bed
```

# Read the data
```{r read-data}
input_tsv
breakpoints_orig <- read_tsv(input_tsv, col_types = cols(Rname = col_character()))
glimpse(breakpoints_orig)

breakpoints <- breakpoints_orig %>% select(Rname, Pos)

input_fai
fai <- read_tsv(input_fai, col_names = c("Rname", "Pos"), col_types = "ci---")
glimpse(fai)
```

# Determine coordinates of subsequences
```{r transform}
bed <- rbind(breakpoints, mutate(fai, Pos = 0L), fai) %>%
	arrange(!is.na(as.integer(Rname)), as.integer(Rname), Rname, Pos) %>%
	mutate(Start = Pos, End = lead(Pos)) %>%
	select(-Pos) %>%
	drop_na() %>%
	filter(Start <= End) %>%
	mutate(Name = make_unique(Rname))
glimpse(bed)
```

# Write the BED file to disk
```{r write-results}
output_bed
bed %>% write_tsv(output_bed, col_names = FALSE)
```

# Coordinates of subsequences
```{r table}
bed
```
